version: "3.9"

services:
  # Laravel backend
  backend:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: url-to-html-backend
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/php/myphp.ini:/usr/local/etc/php/conf.d/myphp.ini
      - /var/www/node_modules
      - vendor_composer:/var/www/vendor/composer
      - storage_framework:/var/www/storage/framework
      - bootstrap_cache:/var/www/bootstrap/cache
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1

  # Nginx
  web:
    image: nginx:latest
    container_name: url-to-html-nginx
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - backend
      - node

  # MySQL
  db:
    image: mysql:8.0
    container_name: url-to-html-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: url-to-html-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

  # Composer
  composer:
    image: composer:latest
    container_name: url-to-html-composer
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - app-network
    command: tail -f /dev/null

  # Node.js (Vite / npm)
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: url-to-html-node
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - app-network
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

volumes:
  dbdata:
  vendor_composer:
  storage_framework:
  bootstrap_cache:

networks:
  app-network:
    driver: bridge
